In [1]:

import pandas as pd
import numpy as np
subjects = ['國文', '英文', '數學', '地理', '歷史']
scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores, columns=subjects, index=range(1, 51))
scores_sum = scores_df.sum(axis=1)
scores_average = scores_df.mean(axis=1)
scores_df

    國文  英文  數學  地理   歷史
1   86  63  82  85   95
2   83  54  71  90   58
3   72  71  63  54   77
4   81  61  91  68   81
5   52  87  88  67   98
6   50  53  70  96   63
7   54  67  65  60   81
8   69  60  61  99   51
9   64  90  60  53   80
10  71  61  92  83  100
11  89  62  70  93   85
12  55  99  85  98   93
13  99  50  96  61   91
14  84  71  87  66   88
15  87  71  99  61   94
16  52  51  84  95   96
17  93  51  85  74   58
18  86  62  94  92   70
19  80  96  80  55   59
20  51  64  75  80   72
21  87  74  93  78   91
22  80  78  82  84   59
23  91  68  98  64   52
24  94  69  66  68   75
25  86  78  64  62   79
26  68  67  81  65   59
27  80  75  98  78   59
28  70  54  62  89   53
29  66  51  56  78   72
30  84  89  83  76   92
31  95  59  63  90   55
32  66  82  70  84   77
33  58  65  86  93   98
34  91  80  83  69   67
35  68  80  66  79   62
36  93  74  84  50   76
37  52  68  69  77   85
38  71  61  80  71   62
39  84  95  57  70   92
40  81  69  75  62   69
41  68  80  74  92   69
42  51  75  50  57   85
43  91  76  75  65   79
44  86  64  57  75   78
45  76  80  58  51   53
46  61  78  75  61   75
47  86  97  97  85   53
48  53  95  61  66   85
49  70  62  68  51   76
50  76  81  51  84   51

In [3]:
from pandas import Series
def a(v:Series):
    return Series([v.max(),v.min(),v.mean()],index=["max","min","av"])
scores_df.apply(a)

        國文     英文    數學     地理      歷史
max  99.00  99.00  99.0  99.00  100.00
min  50.00  50.00  50.0  50.00   51.00
av   74.82  71.36  75.6  74.08   74.56